---
- hosts: jenkins_ec2_slave
  become: true
  gather_facts: true
  tasks:
    - name: Installing Docker Prerequisite packages
      yum: 
        name={{item}}
        state=latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Add extras repository
      shell: yum-config-manager --enable extras
    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y"
    - name: Starting and Enabling Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Pull default Docker image
      docker_image:
        name: voodoo3000/docker-nodejs-demo
        source: pull
