---
- hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Installing Docker Prerequisite packages
      yum:
        name={{item}}
        state=latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: download get-pip.py
      get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
    - name: install pip
      command: "python /tmp/get-pip.py"
    - name: delete get-pip.py
      file: state=absent path=/tmp/get-pip.py
    - name: Add extras repository
      shell: yum-config-manager --enable extras
    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y"
    - name: install docker-py
      pip:
        name: docker-py>=1.7.0
    - name: Starting and Enabling Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Pull default Docker image
      docker_image:
        name: voodoo3000/docker-nodejs-demo
        source: pull
    - name: Create a data container
      docker_container:
        name: nodejs_app
        image: voodoo3000/docker-nodejs-demo
        state: started
        ports:
         - "3000:3000"
